apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypoly-postgres-pvc
  namespace: mypoly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
