version: '3.8'
services:
  db:
    image: postgres:15
    container_name: mypoly-postgres
    env_file:
      - ./user-service/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  user-service:
    build:
      context: ./user-service
      dockerfile: ../Dockerfile
    container_name: mypoly-user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    env_file:
      - ./user-service/.env
    depends_on:
      - db
volumes:
  db_data:
