version: '3.8'
services:
  db:
    image: postgres:15
    container_name: mypoly-postgres
    environment:
      - POSTGRES_USER=mypoly
      - POSTGRES_PASSWORD=mypoly1234
      - POSTGRES_DB=mypoly
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  user-service:
    build:
      context: ./user-service
      dockerfile: ../Dockerfile
    container_name: mypoly-user-service
    environment:
      - KAKAO_CLIENT_ID=f86bfc2d6a9d104e44dc86283047333a
      - KAKAO_CLIENT_SECRET=To1AMzjIyBzTB79Nhuahmm7nEnV0EUjk
      - DB_URL=jdbc:postgresql://db:5432/mypoly
      - DB_USERNAME=mypoly
      - DB_PASSWORD=mypoly1234
    ports:
      - "8082:8082"
    depends_on:
      - db
volumes:
  db_data:
