SET search_path TO bill_service;

ALTER TABLE bill_categories
    ADD COLUMN text_color VARCHAR(6);

UPDATE bill_categories
SET text_color = CASE code
    WHEN 'BROADCAST' THEN '373303'
    WHEN 'WELFARE' THEN '373303'
    WHEN 'LABOR' THEN '373303'
    WHEN 'CHILD' THEN '373303'
    WHEN 'DIGITAL' THEN '181B2A'
    WHEN 'ECONOMY' THEN '181B2A'
    WHEN 'EDUCATION' THEN '181B2A'
    WHEN 'FOREIGN_DEFENSE' THEN '181B2A'
    WHEN 'SECURITY' THEN '0C300C'
    WHEN 'ENVIRONMENT' THEN '0C300C'
    WHEN 'TRANSPORT' THEN '0C300C'
    WHEN 'MEDICAL' THEN '0C300C'
    WHEN 'FAMILY' THEN '0C300C'
    WHEN 'REAL_ESTATE' THEN '503838'
    WHEN 'WOMEN' THEN '503838'
    WHEN 'SEX_CRIME' THEN '503838'
    WHEN 'LAW_ADMIN' THEN '503838'
END
WHERE code IN (
    'BROADCAST', 'WELFARE', 'LABOR', 'CHILD',
    'DIGITAL', 'ECONOMY', 'EDUCATION', 'FOREIGN_DEFENSE',
    'SECURITY', 'ENVIRONMENT', 'TRANSPORT', 'MEDICAL', 'FAMILY',
    'REAL_ESTATE', 'WOMEN', 'SEX_CRIME', 'LAW_ADMIN'
);

ALTER TABLE bill_categories
    ALTER COLUMN text_color SET NOT NULL;
