SET search_path TO bill_service;

ALTER TABLE bill_categories
    ADD COLUMN background_color VARCHAR(6);

UPDATE bill_categories
SET background_color = CASE code
    WHEN 'DIGITAL' THEN '46D9E3'
    WHEN 'SECURITY' THEN '104E7A'
    WHEN 'BROADCAST' THEN 'B6B1FF'
    WHEN 'ECONOMY' THEN 'FFEFC2'
    WHEN 'REAL_ESTATE' THEN 'E2EDFF'
    WHEN 'TRANSPORT' THEN 'FFCFCF'
    WHEN 'ENVIRONMENT' THEN 'ECFFE0'
    WHEN 'MEDICAL' THEN 'D5FFF7'
    WHEN 'WELFARE' THEN 'ACB9FF'
    WHEN 'EDUCATION' THEN '2E3D5E'
    WHEN 'LABOR' THEN '116099'
    WHEN 'WOMEN' THEN 'FED6E1'
    WHEN 'FAMILY' THEN 'A5B4FF'
    WHEN 'CHILD' THEN 'AEEE87'
    WHEN 'SEX_CRIME' THEN 'A45BE3'
    WHEN 'FOREIGN_DEFENSE' THEN 'A2FBE5'
    WHEN 'LAW_ADMIN' THEN '4038DA'
END
WHERE code IN (
    'DIGITAL', 'SECURITY', 'BROADCAST', 'ECONOMY', 'REAL_ESTATE', 'TRANSPORT',
    'ENVIRONMENT', 'MEDICAL', 'WELFARE', 'EDUCATION', 'LABOR', 'WOMEN',
    'FAMILY', 'CHILD', 'SEX_CRIME', 'FOREIGN_DEFENSE', 'LAW_ADMIN'
);

ALTER TABLE bill_categories
    ALTER COLUMN background_color SET NOT NULL;
