# 로컬 개발용 설정(로그/Swagger/SQL)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 디버깅용 로그 레벨 (SQL, 바인딩, 트랜잭션)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.level.org.springframework.transaction=TRACE
logging.level.com.zaxxer.hikari=INFO

# 로컬에서는 Swagger 켬
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
