springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

social.dev-auth.enabled=true
social.dev-auth.key=${DEV_AUTH_KEY:local-dev-key}

# social.google.allowed-audiences=714490493102-d26i4c6magpkh6f4brhi2dvml3d0idbd.apps.googleusercontent.com,714490493102-7t2uuej1thbk0oghfsf23bo9fgbjknsp.apps.googleusercontent.com,714490493102-jn4as4kqgt0c6chgd2vvlc7j6jkviv8i.apps.googleusercontent.com