# 운영/배포용 설정(보수적으로)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# 운영은 Swagger 끔
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# 운영 로그는 기본(INFO) 사용 권장