apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mypoly
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
