apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-ingress
  namespace: mypoly
  annotations:
    # HTTP only (SSL은 나중)
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # /users/** 로 들어온 요청을 user-service의 기존 루트 엔드포인트로 전달하기 위한 rewrite
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: api-mypoly.kro.kr
      http:
        paths:
          - path: /users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 80
