apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterissuers.yaml
  - api-mypoly-cert.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
