apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterissuers.yaml
  - api-mypoly-cert.yaml

  - infra/postgres
  - infra/jwt
  - infra/internal-api
  - services/user-service
  - services/bill-service
  - services/notification-service
  - services/admin-tool
  - services/bill-batch-cronjob
  - services/bill-member-sync-cronjob