apiVersion: v1
kind: Service
metadata:
  name: mypoly-postgres
  namespace: mypoly
spec:
  ports:
    - port: 5432
  selector:
    app: mypoly-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypoly-postgres
  namespace: mypoly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypoly-postgres
  template:
    metadata:
      labels:
        app: mypoly-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: mypoly
            - name: POSTGRES_USER
              value: mypoly
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mypoly-postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
