apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patchesStrategicMerge:
  - patch-configmap.yaml
  - patch-deployment.yaml

# dev 환경에서 도메인이 다르면 patch-ingress.yaml로 host를 바꾸세요.
# patchesStrategicMerge:
#   - patch-ingress.yaml
